apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 100M